# Generated by Django 4.2.13 on 2024-07-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='numero_telefono',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='numero_telefono',
        ),
        migrations.AddField(
            model_name='marca',
            name='razon_social',
            field=models.CharField(default='Valor Predeterminado', max_length=60),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='deportistas_interes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deportista',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Invitados',
        ),
    ]
