# Generated by Django 4.2.13 on 2024-08-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite.usuario')),
                ('especialidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='deportista',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='numero_telefono',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='numero_telefono',
        ),
        migrations.AddField(
            model_name='marca',
            name='razon_social',
            field=models.CharField(default='Coloca el nombre de tu empresa', max_length=60),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='deportistas_interes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
