# Generated by Django 4.2.13 on 2024-08-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0002_remove_marca_apellido_remove_marca_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite.usuario')),
                ('especialidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='deportista',
            name='edad',
        ),
    ]
