# Generated by Django 4.2.13 on 2024-08-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0004_remove_usuario_numero_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
