# Generated by Django 4.2.13 on 2024-08-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0005_usuario_numero_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('numero_telefono', models.IntegerField()),
            ],
        ),
    ]
