# Generated by Django 4.2.13 on 2024-08-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0006_invitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='razon_social',
            field=models.CharField(default='Coloca el nombre de tu empresa', max_length=60),
        ),
    ]
