# Generated by Django 4.2.13 on 2024-08-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0007_alter_marca_razon_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='deporte',
        ),
        migrations.AddField(
            model_name='deporte',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deporte',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite.deportista'),
        ),
    ]
