# Generated by Django 4.2.13 on 2024-08-08 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0008_remove_deportista_deporte_deporte_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='id',
        ),
        migrations.AlterField(
            model_name='deporte',
            name='deportista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite.deportista'),
        ),
    ]
